version: 2

dist: .dist

before:
  hooks:
    - go mod download

builds:
  - id: gop
    main: ./cmd/gop
    binary: bin/gop
    ldflags:
      - -X github.com/goplus/gop/env.buildVersion=v{{.Version}}
      - -X github.com/goplus/gop/env.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      {{.ProjectName}}{{.Version}}.{{.Os}}-{{.Arch}}
      {{- if .Arm}}v{{.Arm}}{{end}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - "*.mod"
      - "*.sum"
      - "*.md"
      - "**/*.go"
      - "**/*.md"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

winget:
  - name: goplus
    homepage: "https://goplus.org/"
    publisher: goplus
    publisher_url: https://github.com/goplus/gop
    publisher_support_url: "https://github.com/goplus/gop/issues/new"
    package_identifier: goplus.gop
    path: "manifests/g/goplus/gop/{{.Version}}"
    tags:
      - golang
      - go
      - gop
      - goplus
      - programming
      - language
      - compiler
      - interpreter
      - data science
      - engineering
      - education
    short_description: The Go+ Programming Language
    description: |
      The Go+ programming language is designed for engineering, STEM education, and data science.
      - For engineering: working in the simplest language that can be mastered by children.
      - For STEM education: studying an engineering language that can be used for work in the future.
      - For data science: communicating with engineers in the same language.
    license: Apache-2.0
    skip_upload: auto
    release_notes: "{{.Changelog}}"
    release_notes_url: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/gop/releases/tag/v{{.Version}}"
    dependencies:
      - package_identifier: GoLang.Go
        minimum_version: 1.18.0
    repository:
      owner: goplus
      name: winget-pkgs
      branch: "{{.ProjectName}}-v{{.Version}}"
      git:
        url: "git@github.com:{{ .Env.GITHUB_REPOSITORY_OWNER }}/winget-pkgs.git"
        private_key: "{{ .Env.WINGET_PKGS_PRIVATE_KEY }}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

checksum:
  name_template: "{{ .ProjectName }}{{ .Version }}.checksums.txt"

release:
  prerelease: auto
