name: Release Build

on:
  push:
    tags:
      - "v*"
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Checkout tag
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        tag_name="${GITHUB_REF##*/}"
        echo Current tag: $tag_name
        git checkout $tag_name
        echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.20"
    
    - name: Install goreleaser
      run: |
        go install github.com/goreleaser/goreleaser@latest

    - name: Release
      run: goreleaser release
