name: Release Build

on:
  push:
    tags:
      - "v*"
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Checkout tag
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        tag_name="${GITHUB_REF##*/}"
        echo Current tag: $tag_name
        git checkout $tag_name
        echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
    
    - name: Check VERSION consistency
      run: |
        tag_name=$(git describe --tags --dirty)
        version=$(cat VERSION)
        echo "VERSION=${version}"
        echo "TAG_NAME=${tag_name}"
        if [ "$tag_name" != "$version" ]; then
          echo "VERSION file is not consistent with tag name"
          exit 1
        fi

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.21"
    
    - name: Install goreleaser
      run: |
        go install github.com/goreleaser/goreleaser@latest

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goreleaser release
